application: kxyktools
version: 17
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /static
  static_dir: static

- url: /love
  static_files: static/love.html
  upload: static/love.html
  
- url: .*
  script: main.py
